#!/usr/bin/env bash
#A linha acima, tambem conhecida como SHEBANG define o interpretador
#de comando deste script.
# ---------------------------------------------------------------- #
# Nome do script:       script_omega.sh
# -----------------------------------------------------------------#
# Descrição:            Script Deselvolvido com apoio do instrutores
#                       Joatham Pedro e do Jonathan Abrantes atraves
#                       do curso da 4Linux 703 - SysAdm.
# -----------------------------------------------------------------#
# Site:                 
# Linkedin:             www.linkedin.com/in/fabiocprates/
# Escrito por:          Fabio Coelho Prates
# Mantido por:          Fabio Coelho Prates
# ---------------------------------------------------------------- #
# Modo de usar: 
#                       Abra o Terminal, acesse o local do script e
#                       permita execução do mesmo.
# Comando p/ exec.      #chmod +x script_omega.sh
# Execute o script:     #./script_omega.sh
# -----------------------------------------------------------------#
# Historico
# Criacao de Menu do Script                              27/09/2022
# Funcoes da opcao 1 - Atualização do sistema            27/09/2022
# Funcoes da opcao 2 - Analise de hosts na Rede Local    28/09/2022
# Funcoes da opcao 3 - Descritivo das Interfaces de rede e descricao
# das portas abertas com nmap localhost                  28/09/2022
# Funcoes da opcao 4 - Verificacao por Rootkits          30/09/2022
# Funcoes da opcao 5 - Backup de arquivos/diretorios     30/09/2022
# -----------------------------------------------------------------#
#=====================VARIAVEIS DECLARADAS========================
TODAY=$(date +%d-%m-%Y-%H-%M-%S)
#=================================================================
clear
echo -e "Este script possui \e[01;31mCOMENTARIOS\e[00m. Não deixe de verifica-los!!!"
sleep 3
echo -e "Para verificar os comentarios use \e[01;31mcat script_omega.sh | less\e[00m."
sleep 7
while :
do
echo `clear`
echo ""
echo "............................................................ "
echo -e "\e[01;32m## SCRIPT OMEGA - SYSADMIN ##\e[00m "
echo -e "Data: \e[01;33m$(date +%d-%m-%Y-%H-%M-%S)\e[00m"
echo "............................................................ "
echo ""
echo -e "Nome da Maquina: \e[01;33m`hostname`\e[00m"
echo -e "O nome do usuário desta máquina é: \e[01;33m`whoami`\e[00m"
echo -e "O sistema operacional que roda nessa máquina é: \e[01;33m`uname -o`\e[00m"
echo -e "O Kernel é: \e[01;33m`uname -r`\e[00m"
echo -e "O diretório home de \e[01;33m`whoami`\e[00m é: \e[01;33m$HOME\e[00m"
echo -e "Tempo de atividade: \e[01;33m$(uptime)\e[00m."
echo ""
echo " Opções: "
echo ""
echo " 1) Atualização do sistema - apt update..."
echo " 2) Analise de hosts na Rede Local "
echo " 3) Servicos da Rede"
echo " 4) Executar o programa para verificacao de RootKit's ?? "
echo " 5) Script para backup local "
echo " 6) Gostaria de visualizar o arquivo /var/log/messages ??"
echo " 7) Desligar ou Reiniciar a maquina ?? "
echo " 8) Sair "
read opcao
case $opcao in
#DESCOMENTE AS LINHAS 87 e 88 SE PRECISAR ADICIONAR FLATPAK E SNAP
1)
clear
echo "Observacao: Caso precise atualizar pacotes flatpak e snap"
sleep 3
echo  "edite este script e descomente as linhas 84 e/ou 85"
sleep 3
echo "Procurando por atualizacoes nos repositorios (apt update)"
sleep 3
apt update
sleep 5
clear
echo "Apresentando atualizacoes localizadas... (apt list --upgradable)"
sleep 3
apt list --upgradable
sleep 10
clear
echo "Instalando atualizações do sistema...(apt upgrade -y)" 
sleep 3
apt upgrade -y
#flatpak update -y
#snap refresh
sleep 5
clear
echo "Limpando o sistema... (apt clean ; apt autoclean)"
sleep 3
apt clean
apt autoclean
sleep 5
clear
echo "Removendo pacotes desnecessários do sistema... (apt remove -y)"
sleep 3
apt remove -y
apt autoremove -y
sleep 5
;;
2)
clear
echo "Listando seus adaptadores com nmcli (nmcli device)"
sleep 2
# Caso o nmcli nao esteja instalado mude para ip link ou ifconfig
nmcli device
#ip link
#ifconfig
sleep 3
echo Agora digite o nome do seu adaptador de rede para o escaneamento.
read adaptador
RESULTADO= netdiscover -i $adaptador -P -r 192.168.1.0/24
sleep 20
;;
3)
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
clear
echo -e "+-----------+-----------------+\n| Interface | IP Address
|\n
+-----------+-----------------+"
for iface in $(ip -o -4 addr list | awk '{print $2}' | tr '\n' ' ')
do
ipaddr=$(ip -o -4 addr list $iface | awk '{print $4}' | cut -d/ -f1)
printf "|%10s | %-16s|\n" $iface $ipaddr
done
echo "+-----------+-----------------+"
echo ""
echo ""
echo ""
echo ""
nmap localhost
echo "Pausado por 20 segundos..."
sleep 20
;;
4)
clear
echo "Para utilizar esta verificacao e necessario instalar o pacote chkrootkit"
sleep 2
echo "Deseja prosseguir com a instalacao?"
sleep 1
echo " sim, nao, pular"
read instalar;
if [ $instalar == "sim" ]
then apt install chkrootkit -y

elif [ $instalar == "nao" ];
then
        echo "Retornando ao menu principal"
        sleep 2  
elif [ $instalar == "pular" ];
then
        echo ""
        echo ""
        echo ""
        echo ""
        echo ""
        clear
        echo " Aguarde Um momento "
        sleep 3
        clear
        echo ""
        echo ""
        exec chkrootkit
        sleep 5
        clear
fi
;;
5)
clear
echo ""
echo ""
echo ""
echo " Script para backup local :"
echo ""
echo "Qual diretorio voce quer realizar o backup?"
read LOCAL;
mkdir -p /root/backups
# Respeitar sempre a sequencia cvjf (J = bz2 | z = gz)
tar -cvjf /root/backups/backup$TODAY.tar.bz2 $LOCAL
sleep 5
echo "Backup realizado"
sleep 5
;;
6)
$diretorio=/var/log/messages
clear
echo "`cat /var/log/messages` "
sleep 10
;;
7)
clear
echo ""
echo " ## Menu para Desligar ou Reiniciar ## "
echo ""
echo ""
echo " Opções: "
echo ""
echo " 1) Desligar (d): "
echo " 2) Reinicar (r): "
echo ""
sleep 2
read dr
clear
test "$dr" = "r" &&{
echo "Realizando Operacao as `date`"
sleep 1
echo " 25%"
sleep 1
echo " 50%"
sleep 1
echo " 75%"
sleep 1
echo " 100%"
sleep 1
clear
echo " .....Reiniciando......."
echo ""
exec shutdown -r now
exit
}
test "$sn" = "d" &&
echo "Realizando Operacao as `date`"
sleep 1
echo " 25%"
sleep 1
echo " 50%"
sleep 1
echo " 75%"
sleep 1
echo " 100%"
sleep 2
clear
echo " .....Desligando......."
sleep 2
exec shutdown -h now
clear
exit
;;
8)
clear
echo ""
echo ""
echo " Gostaria mesmo de sair ( s/n ) ?? "
echo ""
read sn
test "$sn" = "s" &&{
clear
echo ""
echo ""
echo "Script gerado na data e horario de: `date` "
sleep 3
clear
exit
}
test "$sn" = "n" &&
echo ""
clear
echo ""
echo ""
echo " Verifique o botao apertado !!!! "
sleep 2
;;
esac
done
# Notas de Agradecimento.
#
# -----------------------------------------------------------------#
#FIM
